debug: !ENV [ "BOT_DEBUG", "true" ]
file_logs: !ENV [ "FILE_LOGS", "false" ]


bot:
  prefix: "PREFIX"
  token: "TOKEN"
  default_guilds: [ 0000, 1111, 2222, 3333 ] # Can also just be one guild -> [ 0000 ]
  debug_guild: 0000
  version: "VERSION HERE"

error:
  show_stack_trace: true
  print_errors: true

guilds:
  guild_id_one: 11

channels:
  general: 1000000000

roles:
  example_one: 1234
  example_two: 5678

urls:
  youtube: "https://youtube.com"

style:
  colours:
    blue: 0x3775a8
    bright_green: 0x01d277
    orange: 0xe67e22
    pink: 0xcf84e0
    purple: 0xb734eb
    soft_green: 0x68c290
    soft_orange: 0xf9cb54
    soft_red: 0xcd6d6d
    white: 0xfffffe
    yellow: 0xffd241

redirect_output:
  delete_delay: 15
  delete_invocation: true
